apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.email.example.com
spec:
  group: email.example.com
  names:
    kind: EmailSenderConfig
    listKind: EmailSenderConfigList
    plural: emailsenderconfigs
    singular: emailsenderconfig
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiTokenSecretRef:
                  type: string
                senderEmail:
                  type: string
