apiVersion: v1
kind: ServiceAccount
metadata:
  name: email-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-operator-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["email.example.com"]
  resources: ["emails", "emailsenderconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: email-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: email-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: email-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
